#pragma once

#include <pebble.h>

#include "general_magic_layout.h"

typedef struct {
  uint8_t width;
  uint8_t rows[GENERAL_MAGIC_DIGIT_HEIGHT];
  uint8_t pins[GENERAL_MAGIC_DIGIT_HEIGHT];
} GeneralMagicGlyph;

enum {
  GENERAL_MAGIC_GLYPH_ZERO = 0,
  GENERAL_MAGIC_GLYPH_ONE,
  GENERAL_MAGIC_GLYPH_TWO,
  GENERAL_MAGIC_GLYPH_THREE,
  GENERAL_MAGIC_GLYPH_FOUR,
  GENERAL_MAGIC_GLYPH_FIVE,
  GENERAL_MAGIC_GLYPH_SIX,
  GENERAL_MAGIC_GLYPH_SEVEN,
  GENERAL_MAGIC_GLYPH_EIGHT,
  GENERAL_MAGIC_GLYPH_NINE,
  GENERAL_MAGIC_GLYPH_COLON,
  GENERAL_MAGIC_GLYPH_COUNT
};

extern const GeneralMagicGlyph GENERAL_MAGIC_GLYPHS[GENERAL_MAGIC_GLYPH_COUNT];
